//////////////////////////////////////////////////////////////////////
// This file was auto-generated by CodeLite's wxCrafter Plugin
// wxCrafter project file: wxTerminalUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxTerminalUI.hpp"

// Declare the bitmap loading function
extern void wxCrafterntzRqwInitBitmapResources();

namespace {
// return the wxBORDER_SIMPLE that matches the current application theme
[[maybe_unused]]
wxBorder get_border_simple_theme_aware_bit() {
#if wxVERSION_NUMBER >= 3300 && defined(__WXMSW__)
  return wxSystemSettings::GetAppearance().IsDark() ? wxBORDER_SIMPLE
                                                    : wxBORDER_DEFAULT;
#else
  return wxBORDER_DEFAULT;
#endif
} // get_border_simple_theme_aware_bit
bool bBitmapLoaded = false;
} // namespace

SettingsBaseDlg::SettingsBaseDlg(wxWindow *parent, wxWindowID id,
                                 const wxString &title, const wxPoint &pos,
                                 const wxSize &size, long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterntzRqwInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer126 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer126);

  m_panel127 = new wxPanel(this, wxID_ANY, wxDefaultPosition,
                           wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

  boxSizer126->Add(m_panel127, 1, wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer128 = new wxBoxSizer(wxVERTICAL);
  m_panel127->SetSizer(boxSizer128);

  m_notebook132 =
      new wxNotebook(m_panel127, wxID_ANY, wxDefaultPosition,
                     wxDLG_UNIT(m_panel127, wxSize(-1, -1)), wxBK_DEFAULT);
  m_notebook132->SetName(wxT("m_notebook132"));

  boxSizer128->Add(m_notebook132, 1, wxALL | wxEXPAND, WXC_FROM_DIP(10));

  m_panel171 =
      new wxPanel(m_notebook132, wxID_ANY, wxDefaultPosition,
                  wxDLG_UNIT(m_notebook132, wxSize(-1, -1)), wxTAB_TRAVERSAL);
  m_notebook132->AddPage(m_panel171, _("General"), true);

  wxFlexGridSizer *flexGridSizer172 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer172->SetFlexibleDirection(wxBOTH);
  flexGridSizer172->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer172->AddGrowableCol(1);
  m_panel171->SetSizer(flexGridSizer172);

  m_staticText173 = new wxStaticText(m_panel171, wxID_ANY, _("New Tab Title:"),
                                     wxDefaultPosition,
                                     wxDLG_UNIT(m_panel171, wxSize(-1, -1)), 0);

  flexGridSizer172->Add(m_staticText173, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlTitle =
      new wxTextCtrl(m_panel171, wxID_ANY, wxT("Terminal"), wxDefaultPosition,
                     wxDLG_UNIT(m_panel171, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlTitle->SetHint(wxT(""));
#endif

  flexGridSizer172->Add(m_textCtrlTitle, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  flexGridSizer172->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));

  m_checkBoxCloseButton = new wxCheckBox(
      m_panel171, wxID_ANY, _("Show Close Button on Tab"), wxDefaultPosition,
      wxDLG_UNIT(m_panel171, wxSize(-1, -1)), 0);
  m_checkBoxCloseButton->SetValue(true);

  flexGridSizer172->Add(m_checkBoxCloseButton, 0, wxALL | wxEXPAND,
                        WXC_FROM_DIP(5));

  m_panel133 =
      new wxPanel(m_notebook132, wxID_ANY, wxDefaultPosition,
                  wxDLG_UNIT(m_notebook132, wxSize(-1, -1)), wxTAB_TRAVERSAL);
  m_notebook132->AddPage(m_panel133, _("Theme"), false);

  wxBoxSizer *boxSizer149 = new wxBoxSizer(wxVERTICAL);
  m_panel133->SetSizer(boxSizer149);

  wxStaticBoxSizer *staticBoxSizer160 = new wxStaticBoxSizer(
      new wxStaticBox(m_panel133, wxID_ANY, _("General:")), wxVERTICAL);

  boxSizer149->Add(staticBoxSizer160, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer134 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer134->SetFlexibleDirection(wxBOTH);
  flexGridSizer134->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer134->AddGrowableCol(1);

  staticBoxSizer160->Add(flexGridSizer134, 1, wxALL | wxEXPAND,
                         WXC_FROM_DIP(5));

  m_staticText146 =
      new wxStaticText(m_panel133, wxID_ANY, _("Name:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer134->Add(m_staticText146, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  wxArrayString m_choiceNamesArr;
  m_choiceNames =
      new wxChoice(m_panel133, wxID_ANY, wxDefaultPosition,
                   wxDLG_UNIT(m_panel133, wxSize(-1, -1)), m_choiceNamesArr, 0);

  flexGridSizer134->Add(m_choiceNames, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText135 = new wxStaticText(m_panel133, wxID_ANY,
                                     _("Background Colour:"), wxDefaultPosition,
                                     wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer134->Add(m_staticText135, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerBg = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer134->Add(m_colourPickerBg, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText137 = new wxStaticText(m_panel133, wxID_ANY, _("Text Colour:"),
                                     wxDefaultPosition,
                                     wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer134->Add(m_staticText137, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerFg = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer134->Add(m_colourPickerFg, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxStaticBoxSizer *staticBoxSizer159 = new wxStaticBoxSizer(
      new wxStaticBox(m_panel133, wxID_ANY, _("Colours:")), wxVERTICAL);

  boxSizer149->Add(staticBoxSizer159, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer150 = new wxFlexGridSizer(0, 4, 0, 0);
  flexGridSizer150->SetFlexibleDirection(wxBOTH);
  flexGridSizer150->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer150->AddGrowableCol(1);
  flexGridSizer150->AddGrowableCol(3);

  staticBoxSizer159->Add(flexGridSizer150, 1, wxALL | wxEXPAND,
                         WXC_FROM_DIP(5));

  m_staticText151 =
      new wxStaticText(m_panel133, wxID_ANY, _("Black:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer150->Add(m_staticText151, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerBlack = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer150->Add(m_colourPickerBlack, 0, wxALL, WXC_FROM_DIP(5));

  m_staticText153 =
      new wxStaticText(m_panel133, wxID_ANY, _("Red:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer150->Add(m_staticText153, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerRed = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer150->Add(m_colourPickerRed, 0, wxALL, WXC_FROM_DIP(5));

  m_staticText155 =
      new wxStaticText(m_panel133, wxID_ANY, _("Green:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer150->Add(m_staticText155, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerGreen = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer150->Add(m_colourPickerGreen, 0, wxALL, WXC_FROM_DIP(5));

  m_staticText157 =
      new wxStaticText(m_panel133, wxID_ANY, _("Yellow:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer150->Add(m_staticText157, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerYellow = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer150->Add(m_colourPickerYellow, 0, wxALL, WXC_FROM_DIP(5));

  m_staticText161 =
      new wxStaticText(m_panel133, wxID_ANY, _("Blue"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer150->Add(m_staticText161, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerBlue = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer150->Add(m_colourPickerBlue, 0, wxALL, WXC_FROM_DIP(5));

  m_staticText163 =
      new wxStaticText(m_panel133, wxID_ANY, _("Magenta:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer150->Add(m_staticText163, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerMagent = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer150->Add(m_colourPickerMagent, 0, wxALL, WXC_FROM_DIP(5));

  m_staticText165 =
      new wxStaticText(m_panel133, wxID_ANY, _("Cyan:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer150->Add(m_staticText165, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerCyan = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer150->Add(m_colourPickerCyan, 0, wxALL, WXC_FROM_DIP(5));

  m_staticText167 =
      new wxStaticText(m_panel133, wxID_ANY, _("White:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);

  flexGridSizer150->Add(m_staticText167, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_colourPickerWhite = new wxColourPickerCtrl(
      m_panel133, wxID_ANY, *wxBLACK, wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxCLRP_DEFAULT_STYLE);

  flexGridSizer150->Add(m_colourPickerWhite, 0, wxALL, WXC_FROM_DIP(5));

  m_staticLine170 =
      new wxStaticLine(m_panel133, wxID_ANY, wxDefaultPosition,
                       wxDLG_UNIT(m_panel133, wxSize(-1, -1)), wxLI_HORIZONTAL);

  staticBoxSizer159->Add(m_staticLine170, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_checkBoxBrightColours = new wxCheckBox(
      m_panel133, wxID_ANY, _("Show Bright Colours"), wxDefaultPosition,
      wxDLG_UNIT(m_panel133, wxSize(-1, -1)), 0);
  m_checkBoxBrightColours->SetValue(false);

  staticBoxSizer159->Add(m_checkBoxBrightColours, 0, wxALL, WXC_FROM_DIP(5));

  m_stdBtnSizer129 = new wxStdDialogButtonSizer();

  boxSizer128->Add(m_stdBtnSizer129, 0, wxALL | wxALIGN_CENTER_HORIZONTAL,
                   WXC_FROM_DIP(5));

  m_button130 = new wxButton(m_panel127, wxID_OK, wxT(""), wxDefaultPosition,
                             wxDLG_UNIT(m_panel127, wxSize(-1, -1)), 0);
  m_button130->SetDefault();
  m_stdBtnSizer129->AddButton(m_button130);

  m_button131 =
      new wxButton(m_panel127, wxID_CANCEL, wxT(""), wxDefaultPosition,
                   wxDLG_UNIT(m_panel127, wxSize(-1, -1)), 0);
  m_stdBtnSizer129->AddButton(m_button131);
  m_stdBtnSizer129->Realize();

#if wxVERSION_NUMBER >= 2900
  if (!wxPersistenceManager::Get().Find(m_notebook132)) {
    wxPersistenceManager::Get().RegisterAndRestore(m_notebook132);
  } else {
    wxPersistenceManager::Get().Restore(m_notebook132);
  }
#endif

  SetName(wxT("SettingsBaseDlg"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
  // Connect events
  m_choiceNames->Bind(wxEVT_COMMAND_CHOICE_SELECTED,
                      &SettingsBaseDlg::OnThemeChanged, this);
  m_colourPickerBg->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                         &SettingsBaseDlg::OnBackgroundColour, this);
  m_colourPickerFg->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                         &SettingsBaseDlg::OnTextColour, this);
  m_colourPickerBlack->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                            &SettingsBaseDlg::OnBlack, this);
  m_colourPickerRed->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                          &SettingsBaseDlg::OnRed, this);
  m_colourPickerGreen->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                            &SettingsBaseDlg::OnGreen, this);
  m_colourPickerYellow->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                             &SettingsBaseDlg::OnYellow, this);
  m_colourPickerBlue->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                           &SettingsBaseDlg::OnBlue, this);
  m_colourPickerMagent->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                             &SettingsBaseDlg::OnMagenta, this);
  m_colourPickerCyan->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                           &SettingsBaseDlg::OnCyan, this);
  m_colourPickerWhite->Bind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                            &SettingsBaseDlg::OnWhite, this);
  m_checkBoxBrightColours->Bind(wxEVT_COMMAND_CHECKBOX_CLICKED,
                                &SettingsBaseDlg::OnShowBrightColours, this);
}

SettingsBaseDlg::~SettingsBaseDlg() {
  m_choiceNames->Unbind(wxEVT_COMMAND_CHOICE_SELECTED,
                        &SettingsBaseDlg::OnThemeChanged, this);
  m_colourPickerBg->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                           &SettingsBaseDlg::OnBackgroundColour, this);
  m_colourPickerFg->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                           &SettingsBaseDlg::OnTextColour, this);
  m_colourPickerBlack->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                              &SettingsBaseDlg::OnBlack, this);
  m_colourPickerRed->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                            &SettingsBaseDlg::OnRed, this);
  m_colourPickerGreen->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                              &SettingsBaseDlg::OnGreen, this);
  m_colourPickerYellow->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                               &SettingsBaseDlg::OnYellow, this);
  m_colourPickerBlue->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                             &SettingsBaseDlg::OnBlue, this);
  m_colourPickerMagent->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                               &SettingsBaseDlg::OnMagenta, this);
  m_colourPickerCyan->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                             &SettingsBaseDlg::OnCyan, this);
  m_colourPickerWhite->Unbind(wxEVT_COMMAND_COLOURPICKER_CHANGED,
                              &SettingsBaseDlg::OnWhite, this);
  m_checkBoxBrightColours->Unbind(wxEVT_COMMAND_CHECKBOX_CLICKED,
                                  &SettingsBaseDlg::OnShowBrightColours, this);
}
